---
pronombres:
- yo
- tú
- él
- ella
- ello
- nosotros
- vosotros
- ellos
- me
- se
- te
- le
- lo
- nos
- les
- os
- mí
- ti
- usted
- ustedes
- vuestro
- i
- you
- he
- she
- it
- we
- they
- him
- her
- us
- them
- my
- your
- his
- its
- our
- their
- mine
- yours
- hers
- ours
- theirs
- myself
- yourself
- himself
- herself
- ourselves
- yourselves
- themselves
- ich
- du
- er
- sie
- es
- wir
- ihr
- mich
- dich
- ihn
- uns
- euch
- mir
- dir
- ihm
- ihnen
- deiner
- seiner
- unser
- euer
- ihrer
- je
- tu
- il
- elle
- 'on'
- nous
- vous
- ils
- elles
- mon
- ton
- son
- notre
- votre
- leur
- ma
- ta
- sa
- mes
- tes
- ses
- vos
articulos:
- el
- la
- los
- las
- un
- una
- unos
- unas
- the
- an
- der
- ein
- den
- einen
- dem
- einem
- des
- eines
- die
- eine
- einer
- das
- meine
- meinen
- meiner
- une
preposiciones:
- a
- ante
- bajo
- cabe
- con
- contra
- de
- desde
- en
- entre
- hacia
- hasta
- para
- por
- según
- sin
- so
- sobre
- tras
- durante
- mediante
- pro
- versus
- vía
- in
- 'on'
- at
- dans
- derrière
- aus
- mit
- von
- nach
- bis
- für
- ohne
- um
- wegen
- trotz
- innerhalb
- während
- devant
- sur
- sous
- à
- côte
- droite
- gauche
otros:
- del
- don
- doña
- si
- 'no'
- sí
- o
- sic
- vs
conjunciones:
- 'y'
- '&'
- e
- ni
- solo
- sólo
- sino
- así
- como
- cómo
- igual
- mismo
- que
- mas
- más
- pero
- and
- but
- or
- aber
- beziehungsweise
- bzw
- denn
- oder
- sondern
- und
- car
- donc
- et
- mais
- ou
determinantes:
- este
- ese
- aquel
- bastantes
- qué
- cuántos
- mi
- su
- sus
adverbios:
- ahora
- antes
- después
- tarde
- luego
- ayer
- hoy
- mañana
- aquí
- lejos
- cerca
- fuera
- detrás
- encima
- ahí
- arriba
- bien
- mal
- lentamente
- mejor
- peor
- slowly
- easily
- simply
- carefully
- naturally
- happily
- clearly
- fast
- hard
- well
- carelessly
- worse
- separately
- wrong
- badly
- upwards
- downwards
- inwards
- outwards
- forwards
- backwards
- onwards
- homewards
- everywhere
- nowhere
- somewhere
- anywhere
- elsewhere
- up
- down
- here
- there
- near
- nearby
- far
- away
- abroad
- overseas
- in
- out
- inside
- outside
- indoors
- outdoors
- above
- below
- underneath
- beneath
- ahead
- behind
- front
- opposite
- around
- beyond
- aside
- sideways
- back
- over
- all
- now
- early
- late
- soon
- already
- tomorrow
- earlier
- later
- then
- before
- after
- afterwards
- nowadays
- currently
- today
- yesterday
- still
- not
- yet
- longer
- more
- any
- just
- ever
- thereafter
- lately
- recently
- formerly
- latterly
- past
- future
- last
- next
- meanwhile
- shortly
- someday
- ago
- long
- whole
- while
- several
- since
- till
- until
- as
- hereafter
- forever
- eternally
- temporarily
- permanently
- always
- usually
- frequently
- often
- sometimes
- occasionally
- rarely
- seldom
- hardly
- never
- annually
- yearly
- monthly
- weekly
- daily
- hourly
- every
- normally
- regularly
- once
- twice
- first
- initially
- secondly
- thirdly
- fourthly
- lastly
- finally
- eventually
- much
- little
- less
- almost
- nearly
- barely
- scarcely
- partially
- partly
- entirely
- completely
- absolutely
- relatively
- least
- most
- largely
- mostly
- mainly
- totally
- extremely
- altogether
- very
- too
- enough
- only
- pretty
- quite
- fairly
- rather
- certainly
- course
- definitely
- indeed
- obviously
- really
- serely
- truly
- undoubtedly
- likely
- perhaps
- maybe
- possibly
- probably
- 


e_ingles:
- are
- be
- by
- for
- from
- into
- is
- it
- of
- that
- these
- there
- they
- this
- to
- we
- where
- when
- with
numbers:
- ii
- iii
- iv
- v
- vi
- vii
- viii
- ix
- x
- xi
- x
- xi
- xii
- xiii
- xiv
- xv
- xvi
- xvii
- xviii
- xix
- xx
exceptions:
- abstract
- pp
